/*
 * Copyright 2021 HP.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.rwthaachen.wzl.gt.nbm.nbhelp.search.views;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class CreateIndexDialog extends javax.swing.JDialog {

    /**
     * Creates new form CreateIndexDialog
     */
    public CreateIndexDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreate = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblHelpPagesLocation1 = new javax.swing.JLabel();
        txtHelpPagesLocation = new javax.swing.JTextField();
        btnHelpPagesLocationBrowse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.openide.awt.Mnemonics.setLocalizedText(btnCreate, org.openide.util.NbBundle.getMessage(CreateIndexDialog.class, "CreateIndexDialog.btnCreate.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnClose, org.openide.util.NbBundle.getMessage(CreateIndexDialog.class, "CreateIndexDialog.btnClose.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblHelpPagesLocation1, org.openide.util.NbBundle.getMessage(CreateIndexDialog.class, "CreateIndexDialog.lblHelpPagesLocation1.text")); // NOI18N
        lblHelpPagesLocation1.setToolTipText(org.openide.util.NbBundle.getMessage(CreateIndexDialog.class, "CreateIndexDialog.lblHelpPagesLocation1.toolTipText")); // NOI18N

        txtHelpPagesLocation.setText(org.openide.util.NbBundle.getMessage(CreateIndexDialog.class, "CreateIndexDialog.txtHelpPagesLocation.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnHelpPagesLocationBrowse, org.openide.util.NbBundle.getMessage(CreateIndexDialog.class, "CreateIndexDialog.btnHelpPagesLocationBrowse.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 182, Short.MAX_VALUE)
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtHelpPagesLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHelpPagesLocationBrowse))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHelpPagesLocation1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHelpPagesLocation1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHelpPagesLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHelpPagesLocationBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnHelpPagesLocationBrowse;
    private javax.swing.JLabel lblHelpPagesLocation1;
    private javax.swing.JTextField txtHelpPagesLocation;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnClose() {
        return btnClose;
    }

    public JButton getBtnCreate() {
        return btnCreate;
    }

    public JTextField getTxtHelpPagesLocation() {
        return txtHelpPagesLocation;
    }

    public JButton getBtnHelpPagesLocationBrowse() {
        return btnHelpPagesLocationBrowse;
    }
    
}
